# Generated by Django 4.0.6 on 2022-12-23 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartapp', '0002_comment_alter_member_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='fname',
            new_name='Firstname',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='lname',
            new_name='Lastname',
        ),
    ]
