# Generated by Django 4.0.6 on 2023-02-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartapp', '0003_rename_fname_member_firstname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
