# Generated by Django 4.0.6 on 2023-02-08 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartapp', '0005_memberlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='other',
            new_name='others',
        ),
    ]
