# Generated by Django 4.0.6 on 2023-02-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartapp', '0006_rename_other_member_others'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='profession',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='member',
            name='others',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
